version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-cli-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            sudo composer self-update
            composer install -n --prefer-dist
      - run:
          name: "Static analysis"
          command: |
            make static-analysis
      - run:
          name: "Unit tests"
          command: |
            make unit
      - run:
          name: "Coding style"
          command: |
            make check-cs
      - run:
          name: "Mutation tests"
          command: |
            make mutation-test
